### ISSUE TITLE
Simply Plural data does not sync automatically

### ISSUE THREAD

**Issue by MesozoicSystem** [plurali/Plurali#182]
Whenever we make a new alter/member profile on SimplyPlural, Plurali won't update it. No one can figure out how to fix it.

**Comment by lilianalillyy** [comment]
Could I get the link to your profile or your Simply Plural ID?

**Comment by MesozoicSystem** [comment]
> Could I get the link to your profile or your Simply Plural ID?

d53da9a26e79da8d9ca918f1bbddf2da4fcae7f960fbd91ce0cd1f6e11f9f3b2

**Comment by MesozoicSystem** [comment]
Wait no how do I open it again

**Comment by MesozoicSystem** [comment]
Oooh sorry

**Comment by MesozoicSystem** [comment]
Oooh sorry

**Comment by lilianalillyy** [comment]
From what I can see, the only time the Simply Plural data was synced with Plurali was on October 11th, which is weird, could you perhaps do the following steps?

1. Revoke the old key in Simply Plural. This can be done in SP Settings -> Tokens -> Click the red trash icon next to the token you use on Simply Plural
2. In Plurali go to Dashboard -> User settings -> Click on "Update user settings" -> Refresh (F5) the page -> the token field should be empty
3. Create a new token in Simply Plural, enter it to the user settings in Plurali and save it. This should immediately sync up your system and hopefully resolve the issues you've been facing.

Let me know if it helps, if anything you can contact me on Discord - `liliana1110`.

@MesozoicSystem

**Comment by lilianalillyy** [comment]
> From what I can see, the only time the Simply Plural data was synced with Plurali was on October 11th, which is weird, could you perhaps do the following steps?
> 
> 1. Revoke the old key in Simply Plural. This can be done in SP Settings -> Tokens -> Click the red trash icon next to the token you use on Simply Plural
> 2. In Plurali go to Dashboard -> User settings -> Click on "Update user settings" -> Refresh (F5) the page -> the token field should be empty
> 3. Create a new token in Simply Plural, enter it to the user settings in Plurali and save it. This should immediately sync up your system and hopefully resolve the issues you've been facing.
> 
> Let me know if it helps, if anything you can contact me on Discord - `liliana1110`.
> 
> @MesozoicSystem

This apparently solved it (as discussed via Discord), closing the issue then ^^
