### ISSUE TITLE
Plurali is down again and has been for about 2 days

### ISSUE THREAD

**Issue by MesozoicSystem** [plurali/Plurali#225]
![Screenshot_20240506_070913_Chrome](https://github.com/plurali/Plurali/assets/151105535/b4679ec2-adff-47b5-89f5-5c17e4828c2c)
![Screenshot_20240506_070921_Chrome](https://github.com/plurali/Plurali/assets/151105535/c7025f84-29bb-4cf3-a30d-73db63f19517)

**Comment by MesozoicSystem** [comment]
My network is fine, my device is practically brand new, and nothing else including other websites and apps are having any problems.

**Comment by lilianalillyy** [comment]
> My network is fine, my device is practically brand new, and nothing else including other websites and apps are having any problems.

not sure if you have seen, plurali is back up. sorry for the inconvenience.
