### ISSUE TITLE
Issues Logging in/Accessing Site

### ISSUE THREAD

**Issue by BloodMoonNight** [plurali/Plurali#226]
I don’t know if it’s due to a new update or anything but I wanted to ask just to make sure. 
is the site under some form of construction being it has “Network Error” at the top of the screen when attempting to log on.

I apologize if this isn’t how things are normally done on the website, I only got it so I could ask this question.
![IMG_1019](https://github.com/plurali/Plurali/assets/171121994/7c0a5612-092d-48e6-9a24-8f00597b9475)

**Comment by lilianalillyy** [comment]
> I don’t know if it’s due to a new update or anything but I wanted to ask just to make sure. is the site under some form of construction being it has “Network Error” at the top of the screen when attempting to log on.
> 
> I apologize if this isn’t how things are normally done on the website, I only got it so I could ask this question. ![IMG_1019](https://private-user-images.githubusercontent.com/171121994/334686691-7c0a5612-092d-48e6-9a24-8f00597b9475.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDIyNDUsIm5iZiI6MTcxODAwMTk0NSwicGF0aCI6Ii8xNzExMjE5OTQvMzM0Njg2NjkxLTdjMGE1NjEyLTA5MmQtNDhlNi05YTI0LThmMDA1OTdiOTQ3NS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTBUMDY0NTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzYyOTkwM2RkMzYzY2M5MTM0ZDNlYmE2NjFlMGNlZjFlMmJmMmY1ZTcxNzcwYjY1NjZjZGY1OTdjOTJjZTZhNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.W93bpcRxRlHXcKloAW7gW5CUxmFWAg5E50NQp9zBI9I)

the API was down due to some issues with the hosting, hence why the Network Error, as it wasn't able to access it.
