### ISSUE TITLE
Custom Fields showing days of week instead of days of month

### ISSUE THREAD

**Issue by sciencesystem-net** [plurali/Plurali#88]
when looking at custom fields birthday is always wrong

**Comment by lilianalillyy** [comment]
Can you please show an example and/or provide steps to reproduce the issue?

**Comment by sciencesystem-net** [comment]
Examples all from one member but it happens to all of ours (the birthday _should_ be the 11th of October, _not_ the 3rd)

![image_2023-06-04_140634917](https://github.com/plurali/Plurali/assets/135430458/492a2176-eb84-4f92-bb9a-e78c3d35f1ed)
![image_2023-06-04_140649862](https://github.com/plurali/Plurali/assets/135430458/29962708-7c0d-4650-9045-3032e65b7d59)
![image_2023-06-04_140657620](https://github.com/plurali/Plurali/assets/135430458/7da41f8f-cdde-4044-9fc7-4f89763247d5)

**Comment by lilianalillyy** [comment]
May i get a link to your profile so I can look into this bug further?

**Comment by sciencesystem-net** [comment]
https://plurali.icu/EGilxm-themidnightoflostsouls

**Comment by lilianalillyy** [comment]
The issue was fixed and the fix was just deployed, it should work now ^^ (if it still shows the wrong date, try to delete cache in your browser :))
